// data.js — content for Clarity for Complex Work
window.SITE_DATA = {
  founder: "Matteo Calla",
  brand: "Clarity for Complex Work",
  tagline: "Strategic communications for ideas that resist easy summary.",

  credentials: [
    "PhD in Literature, Cornell University",
    "Writing Instructor, Cornell University",
    "6 years experience in Marketing & Sales",
    "Arts Journalist since 2002",
    "Bachelor's degree in both Arts and Sciences",
    "Consulting for NGOs, Tech, and the Arts",
  ],

  credentialsIntro: "My background brings intellectual depth to marketing savvy, allowing me to understand clients across sectors and make their work resonate with the audience they want to reach.",

  catalogue: [
    {
      n: "01",
      slug: "european-climate-foundation",
      client: "European Climate Foundation",
      monogram: "E.C.F.",
      logo: "images/clients/european-climate-foundation.png",
      bg: "#1E8590",
      clientType: "International NGO",
      deliverable: "Funder Presentations",
      desc: "Ongoing collaboration on narrative strategy, copy, and design of funder presentation decks at one of Europe's leading climate foundations, built for boards and major donors.",
      year: "2026",
    },
    {
      n: "02",
      slug: "fired-up-space",
      client: "Fired Up Space",
      monogram: "F.U.S.",
      logo: "images/clients/fired-up-space.png",
      bg: "#E8E5DD",
      noBorder: true,
      clientType: "Social Enterprise",
      deliverable: "Keynote Presentation",
      desc: "Keynote deck and speech for Berlin's People and Culture Festival, turning a social enterprise's approach to job coaching into a compelling case for funders and the general public alike.",
      year: "2025",
    },
    {
      n: "03",
      slug: "claro-ai",
      client: "Claro.AI",
      monogram: "C.AI",
      logo: "images/clients/claro.png",
      bg: "#FFFFFF",
      clientType: "Tech Startup",
      deliverable: "Pitch Deck & Messaging",
      desc: "Pitch deck and web taglines for an AI data platform, translating a complex product into investor-ready language that helped secure another round of funding.",
      year: "2025",
    },
    {
      n: "04",
      slug: "jergon-gallery",
      client: "JERGON Gallery",
      monogram: "J.G.",
      logo: "images/clients/jergon.png",
      bg: "linear-gradient(to bottom, #EE5123 0%, #EE5123 50%, #020003 50%, #020003 100%)",
      borderTop: "#EE5123",
      borderBottom: "#0A0A0A",
      clientType: "Art Gallery",
      deliverable: "Messaging & Positioning Rebrand",
      desc: "Messaging and positioning advisory for a contemporary art gallery in Berlin, translating a sophisticated curatorial vision into clear, audience-ready language across web, press, and social.",
      year: "2025",
    },
    {
      n: "05",
      slug: "john-londono",
      client: "John Londono",
      monogram: "J.L.",
      logo: "images/clients/john-londono.jpg",
      bg: "#0A0A0A",
      clientType: "Artist",
      deliverable: "Exhibition Text",
      desc: "Exhibition text for a solo photography show during the 2025 European Month of Photography, articulating something essential the artist hadn't yet named and bringing it to a wide audience.",
      year: "2025",
    },
    {
      n: "06",
      slug: "michael-janssen-galerie",
      client: "Michael Janssen Galerie",
      monogram: "M.J.G.",
      logo: "images/clients/michael-janssen.png",
      bg: "#FFFFFF",
      clientType: "Art Gallery",
      deliverable: "Artist Talk / Interview",
      desc: "Moderated talk with Angolan artist Yonamine at Michael Janssen Galerie, framing the artist's practice for a live audience with precision, accessibility, and relevance.",
      year: "2024",
    },
  ],

  approach: {
    aphorism: "You can't <em>grow</em><br/>what you don't <em>see</em>.",
    subtitle: "My <em>approach</em>, in three parts.",
    acts: [
      {
        n: "I.",
        label: "The Problem",
        head: "Complex work <em>clouds</em> its own view.",
        body: "The deeper the work, the more it relies on insider language. Outsiders can't see in, and the team loses sight of what it actually does, too.",
      },
      {
        n: "II.",
        label: "The Stakes",
        head: "Clarity <em>is</em> identity.",
        body: "Lack of clarity is more than a comms problem. How an organisation understands itself shapes culture, hiring, and product as much as it shapes every funder pitch, gallery text, and public talk. External communication is internal cohesion.",
      },
      {
        n: "III.",
        label: "My Solution",
        head: "First clarify, <em>then</em> communicate.",
        body: "Most comms focus on the audience. For complex work, that's not enough. I offer an external eye that strips the jargon to clarify what you really mean, the basis for both clear identity and audience-tailored messaging.",
      },
    ],
  },

  services: {
    flagship: {
      sectionKicker: "№ 04 / SERVICES",
      format: "3–5 sessions",
      teaserPitch: "An intensive engagement to find the narrative at the heart of what you do, and the language to share it effectively.",
      pageUrl: "clarity-sessions.html",
      ctaLabel: "About the sessions",
      title: "The Clarity Sessions",
      subtitle: "Excavating your Core Narrative",
      audiences: [
        "For <em>startup founders</em> getting clear on what they're building and for whom.",
        "For <em>artists</em> finding the vocabulary to talk about their work.",
        "For <em>NGOs and foundations</em> whose mission has outgrown the language they use to describe it.",
        "— For anyone seeking clearer messaging, sharper positioning, and a stronger sense of what they stand for.",
      ],
      pitch: "A clear understanding of your work is the basis of both effective external communications and internal cohesion, and the foundation of organisational growth. In conversation and intensive engagement with your materials, I help excavate the core narrative and positioning at the heart of your work. You leave with the language for a public identity, and a clearer understanding of your work itself.",
      involvesLabel: "What the sessions involve",
      involves: [
        "Diagnosing the underlying pattern in your work",
        "Extracting your core theme and conceptual architecture",
        "Identifying what you're really trying to say",
        "Translating this into clean, resonant language",
        "Giving you vocabulary you haven't had for yourself",
      ],
      deliverable: "Sessions are accompanied by a short working document — a distilled reference for your narrative, voice, and positioning that you can use internally and share with anyone working on your communications.",
    },
    subhead: "Available <b>on a project basis</b>, <b>as a monthly retainer</b>, or <b>in a fractional senior comms role</b> — whichever fits the work.",
    audiences: [
      { label: "For Scale-Ups", href: "for-scale-ups.html" },
      { label: "For NGOs & Foundations", href: "for-ngos.html" },
      { label: "For Artists & Institutions", href: "for-artists.html" },
    ],
    rows: [
      {
        label: "Strategic Communications",
        cells: [
          [
            "Pitch decks / investor presentations",
            "Keynote / conference presentations",
            "Messaging and positioning guides",
            "Web and social copy",
          ],
          [
            "Funder presentations",
            "Keynote / conference presentations",
            "Impact reports / annual reports",
            "Donor communications and campaign copy",
            "Press and media materials",
          ],
          [
            "Exhibition and gallery texts",
            "Catalogue essays and forewords",
            "Web and social copy",
            "Artist talks",
            "Press and media materials",
          ],
        ],
      },
      {
        label: "Thought Advisory",
        cells: [
          [
            "Narrative strategy advisory",
            "Founder voice coaching",
            "Communications audit",
          ],
          [
            "Public engagement coaching",
            "Online and social media advisory",
            "Communications audit",
          ],
          [
            "Project consultation",
            "Online self-presentation coaching",
            "Voice and framing coaching",
          ],
        ],
      },
      {
        label: "Workshops & Training",
        cells: [
          [
            "Messaging alignment workshops",
            "Founder storytelling intensive",
          ],
          [
            "Communicating impact workshops",
            "Funder storytelling workshops",
          ],
          [
            "Art-writing workshops",
            "Public engagement workshops",
          ],
        ],
      },
    ],
  },

  testimonials: [
    {
      id: "erlund",
      size: "lg",
      photo: "images/testimonials/sophie-erlund.png",
      quote: "Matteo has a unique ability to frame complex ideas, and was able to capture not only the technical aspects but also the philosophical questions in my work.",
      body: "He approached my topics with dedicated curiosity and created a space for open dialogue, fostering an engaged and enriching conversation.",
      who: "Sophie Erlund",
      org: "Chair of Art in Architecture, TUM",
      city: "Munich",
      initials: "S.E.",
      tone: 1,
    },
    {
      id: "patruno",
      size: "sm",
      photo: "images/testimonials/nicola-patruno.png",
      quote: "My collaboration with Matteo Calla has been very important for my gallery, JERGON, in Berlin and for my work as a curator.",
      body: "He made a decisive contribution in defining my positioning within the Berlin contemporary arts scene and in creating a coherent communications strategy across social media, LinkedIn, and other platforms I use.",
      who: "Nicola Patruno",
      org: "Founder, JERGON Gallery",
      city: "Berlin",
      initials: "N.P.",
      tone: 2,
    },
    {
      id: "hahn",
      size: "sm",
      photo: "images/testimonials/clara-hahn.png",
      quote: "I can wholeheartedly recommend Matteo's work. He is quick to respond and super talented with words.",
      body: "Matteo helped me crystallise the core message, create the presentation, and not only prepare but feel confident about my speech.",
      who: "Clara Hahn",
      org: "Founder, Fired Up Space GmbH",
      city: "Berlin",
      initials: "C.H.",
      tone: 1,
    },
    {
      id: "londono",
      size: "sm",
      photo: "images/testimonials/john-londono.png",
      quote: "Matteo Calla's text for the exhibition captured its essence with rare sensitivity and depth.",
      body: "His thoughtful and intuitive questions led to a nuanced exploration that made me feel deeply understood as an artist. His writing resonates beyond description &mdash; like a quiet echo of the work itself.",
      who: "John Londoño",
      org: "Photographer",
      city: "Brussels",
      initials: "J.L.",
      tone: 3,
    },
    {
      id: "minoliti",
      size: "sm",
      photo: "images/testimonials/ad-minoliti.png",
      quote: "I enjoyed working with Matteo. He was able to write about my project with great clarity and effectively convey its stakes to a wide audience.",
      who: "Ad Minoliti",
      org: "Artist",
      city: "Buenos Aires",
      initials: "A.M.",
      tone: 2,
    },
  ],
  cta: {
    sectionNum: "№ 06 / Correspondence",
    title: 'How we <em>work</em><br/>together.',
    method: [
      { n: "I.",   t: "I listen.",        b: "I start by learning what you do: in conversation with you, and by reading my way through your decks, drafts, transcripts, and the way you actually talk about the work." },
      { n: "II.",  t: "We clarify.",      b: "We analyse and synthesise what you actually do until its core comes into view, and find the language you don't yet have to name it." },
      { n: "III.", t: "We shape for your audience.", b: "Then we shape the message for its audience, format, and goal: funder, founder, gallery wall, or stage." },
    ],
    open: "Tell me more about your work.",
    invite: "Book a free thirty-minute consultation.",
    btnText: "Get in touch",
    email: "matteo@clarityforcomplexwork.com",
  },
};
